export const challenges = [
  {
    id: 'for-noun-make',
    structure: 'For + noun, S + V',
    instruction: 'Bắt đầu với cụm danh từ đứng sau “For”.',
    segments: [
      { text: 'For', context: true },
      { id: 'young-learners', text: 'young learners', suffix: ',' },
      { id: 'especially', text: 'especially' },
      { id: 'those', text: 'those' },
      { id: 'in-primary', text: 'in' },
      { id: 'primary-school', text: 'primary school', suffix: ',' },
      { id: 'visual-aids', text: 'visual aids' },
      { id: 'such-as-charts', text: 'such as' },
      { id: 'charts', text: 'colourful charts' },
      { id: 'make', text: 'make' },
      { id: 'grammar', text: 'grammar' },
      { id: 'easier', text: 'easier', suffix: '.' },
    ],
    steps: [
      { label: 'For + noun', answer: 'young-learners', hint: 'Tìm người hoặc vật đứng ngay sau giới từ “For”.' },
      { label: 'S', answer: 'visual-aids', joinBefore: ',', hint: 'Chủ ngữ chính là thứ thực hiện hành động “make”.' },
      { label: 'V', answer: 'make', pattern: 'make + noun + adj', hint: 'Động từ chính diễn tả việc làm cho điều gì thay đổi.' },
      { label: 'Noun', answer: 'grammar', revealAt: 3, hint: 'Danh từ này là đối tượng chịu tác động của “make”.' },
      { label: 'Adj', answer: 'easier', revealAt: 3, hint: 'Tính từ mô tả trạng thái mới của danh từ.' },
    ],
  },
  {
    id: 'to-reduce-stress',
    structure: 'To + V, S + V + something',
    instruction: 'Tìm trọn cụm hành động chỉ mục đích ở đầu câu.',
    segments: [
      { text: 'To', context: true },
      { id: 'reduce-stress', text: 'reduce stress' },
      { id: 'during', text: 'during' },
      { id: 'semester-a', text: 'a' },
      { id: 'busy-semester', text: 'busy semester', suffix: ',' },
      { id: 'students', text: 'students' },
      { text: 'should', context: true },
      { id: 'prepare', text: 'prepare' },
      { id: 'article-a', text: 'a' },
      { id: 'simple', text: 'simple' },
      { id: 'study-plan', text: 'study plan', suffix: '.' },
    ],
    steps: [
      { label: 'To + V', answer: 'reduce-stress', hint: 'Chọn cả hành động và đối tượng ngay sau “To”.' },
      { label: 'S', answer: 'students', joinBefore: ',', hint: 'Ai nên chuẩn bị kế hoạch?' },
      { label: 'V', answer: 'prepare', hint: '“Should” đã được cho sẵn; chỉ chọn động từ chính.' },
      { label: 'Something', answer: 'study-plan', revealAt: 3, hint: 'Chỉ chọn danh từ chính, không chọn mạo từ hoặc tính từ.' },
    ],
  },
  {
    id: 'participate-in-activities',
    structure: 'S + V + in + noun',
    instruction: 'Tập trung vào chủ ngữ, động từ chính và danh từ sau “in”.',
    segments: [
      { id: 'students', text: 'Students' },
      { text: 'in', context: true },
      { id: 'club-the', text: 'the' },
      { id: 'speaking-club', text: 'speaking club' },
      { text: 'can', context: true },
      { id: 'participate', text: 'participate' },
      { text: 'in', context: true },
      { id: 'numerous', text: 'numerous' },
      { id: 'interesting-activities', text: 'interesting activities' },
      { id: 'such-as-examples', text: 'such as' },
      { id: 'role-play', text: 'role-play games' },
      { text: 'and', context: true },
      { id: 'storytelling', text: 'storytelling sessions', suffix: '.' },
    ],
    steps: [
      { label: 'S', answer: 'students', hint: 'Ai có thể tham gia?' },
      { label: 'V', answer: 'participate', hint: '“Can” đã được cho sẵn; chỉ chọn động từ chính.' },
      { label: 'in + Noun', answer: 'interesting-activities', revealAt: 2, hint: 'Sau “in”, chọn cả cụm tính từ và danh từ đi cùng nhau.' },
    ],
  },
  {
    id: 'teacher-explains-rules',
    structure: 'S + V + something + with + noun',
    instruction: 'Bỏ qua các phần mô tả giáo viên và tìm ba thành phần chính.',
    segments: [
      { text: 'The', context: true },
      { id: 'patient', text: 'particularly patient' },
      { id: 'teacher', text: 'teacher', suffix: ',' },
      { id: 'relative-who', text: 'who' },
      { id: 'relative-works', text: 'works' },
      { id: 'relative-at', text: 'at' },
      { id: 'relative-school', text: 'our school', suffix: ',' },
      { id: 'explains', text: 'explains' },
      { id: 'difficult', text: 'difficult' },
      { id: 'grammar-rules', text: 'grammar rules' },
      { text: 'with', context: true },
      { id: 'clear-examples', text: 'clear examples', suffix: '.' },
    ],
    steps: [
      { label: 'S', answer: 'teacher', hint: 'Chọn danh từ chính chỉ người thực hiện hành động.' },
      { label: 'V', answer: 'explains', hint: 'Động từ chính diễn tả việc giảng giải.' },
      { label: 'Something', answer: 'grammar-rules', revealAt: 2, hint: 'Chọn cụm danh từ chỉ điều được giải thích; không chọn tính từ đứng trước.' },
      { label: 'with + Noun', answer: 'clear-examples', revealAt: 2, hint: 'Sau “with”, chọn cụm danh từ chỉ công cụ hoặc ví dụ được sử dụng.' },
    ],
  },
  {
    id: 'teenagers-enjoy-lessons',
    structure: 'S + V + something',
    instruction: 'Các cụm chỉ nơi chốn và thời gian không thuộc cấu trúc chính.',
    segments: [
      { id: 'many-teenagers', text: 'Many teenagers' },
      { id: 'from', text: 'from' },
      { id: 'small-towns', text: 'small towns' },
      { id: 'particularly', text: 'particularly' },
      { id: 'enjoy', text: 'enjoy' },
      { id: 'online', text: 'online' },
      { id: 'music-lessons', text: 'music lessons' },
      { id: 'after-school', text: 'after school', suffix: '.' },
    ],
    steps: [
      { label: 'S', answer: 'many-teenagers', hint: 'Chọn cả cụm chủ ngữ gồm từ chỉ số lượng và danh từ.' },
      { label: 'V', answer: 'enjoy', hint: 'Từ nào diễn tả sự yêu thích?' },
      { label: 'Something', answer: 'music-lessons', revealAt: 2, hint: 'Chọn cụm danh từ chính; “online” là phần bổ nghĩa được tách riêng.' },
    ],
  },
  {
    id: 'library-offers-spaces',
    structure: 'S + V + somebody + noun',
    instruction: 'Tìm chủ ngữ và động từ trước; mẫu đầy đủ sẽ mở ra ở bước V.',
    segments: [
      { text: 'The', context: true },
      { id: 'library', text: 'library' },
      { id: 'near', text: 'near' },
      { id: 'near-apartment', text: 'our apartment' },
      { id: 'offers', text: 'offers' },
      { id: 'students', text: 'students' },
      { id: 'quiet', text: 'quiet' },
      { id: 'study-spaces', text: 'study spaces' },
      { id: 'weekends', text: 'on weekends', suffix: '.' },
    ],
    steps: [
      { label: 'S', answer: 'library', hint: 'Địa điểm nào cung cấp không gian học?' },
      { label: 'V', answer: 'offers', pattern: 'offer + somebody + noun', hint: 'Động từ chính mang nghĩa “cung cấp”.' },
      { label: 'Somebody', answer: 'students', revealAt: 2, hint: 'Ai nhận được lợi ích?' },
      { label: 'Noun', answer: 'study-spaces', revealAt: 2, hint: 'Chọn cụm danh từ chỉ thứ được cung cấp.' },
    ],
  },
  {
    id: 'sessions-help-learners',
    structure: 'S + V + somebody + V + something',
    instruction: 'Tìm danh từ chính của chủ ngữ trước khi phân tích mẫu “help”.',
    segments: [
      { id: 'daily', text: 'Daily' },
      { id: 'reading-sessions', text: 'reading sessions' },
      { id: 'at-home', text: 'at home' },
      { id: 'help', text: 'help' },
      { id: 'young', text: 'young' },
      { id: 'learners', text: 'learners' },
      { id: 'remember', text: 'remember' },
      { id: 'new', text: 'new' },
      { id: 'words', text: 'words' },
      { id: 'easily', text: 'more easily', suffix: '.' },
    ],
    steps: [
      { label: 'S', answer: 'reading-sessions', hint: 'Chọn cả cụm danh từ “reading sessions”; “Daily” được tách riêng.' },
      { label: 'V', answer: 'help', pattern: 'help + somebody + verb', hint: 'Động từ chính mang nghĩa “giúp”.' },
      { label: 'Somebody', answer: 'learners', revealAt: 2, hint: 'Ai nhận được sự giúp đỡ?' },
      { label: 'Verb', answer: 'remember', revealAt: 2, hint: 'Sau “help + somebody” là hành động nào?' },
      { label: 'Something', answer: 'words', revealAt: 2, hint: 'Chỉ chọn danh từ chính của điều được ghi nhớ.' },
    ],
  },
  {
    id: 'club-organises-experiments',
    structure: 'S + V + something + for + somebody',
    instruction: 'Các cụm chỉ nơi chốn, người hưởng lợi và thời gian là phần gây nhiễu.',
    segments: [
      { text: 'The', context: true },
      { id: 'science-club', text: 'science club' },
      { id: 'at-school', text: 'at' },
      { id: 'our-school', text: 'our school' },
      { id: 'organises', text: 'organises' },
      { id: 'exciting', text: 'exciting' },
      { id: 'experiments', text: 'experiments' },
      { text: 'for', context: true },
      { id: 'students', text: 'students' },
      { id: 'friday', text: 'every Friday', suffix: '.' },
    ],
    steps: [
      { label: 'S', answer: 'science-club', hint: 'Chọn cả cụm danh từ chỉ câu lạc bộ.' },
      { label: 'V', answer: 'organises', hint: 'Từ nào diễn tả việc tổ chức?' },
      { label: 'Something', answer: 'experiments', revealAt: 2, hint: 'Chỉ chọn danh từ chính của hoạt động được tổ chức.' },
      { label: 'for + Somebody', answer: 'students', revealAt: 2, hint: 'Sau “for”, chọn người nhận lợi ích.' },
    ],
  },
  {
    id: 'students-find-passages-difficult',
    structure: 'S + V + noun + adj',
    instruction: 'Mẫu sau V sẽ được mở ra khi bạn xác định xong chủ ngữ.',
    segments: [
      { id: 'some-students', text: 'Some students' },
      { id: 'with-vocabulary', text: 'with' },
      { id: 'limited-vocabulary', text: 'limited vocabulary' },
      { id: 'find', text: 'find' },
      { id: 'long', text: 'long' },
      { id: 'reading-passages', text: 'reading passages' },
      { id: 'particularly', text: 'particularly' },
      { id: 'difficult', text: 'difficult' },
      { id: 'during-tests', text: 'during tests', suffix: '.' },
    ],
    steps: [
      { label: 'S', answer: 'some-students', hint: 'Chọn cả cụm chủ ngữ gồm từ chỉ số lượng và danh từ.' },
      { label: 'V', answer: 'find', pattern: 'find + noun + adj', hint: 'Động từ chính mang nghĩa “nhận thấy”.' },
      { label: 'Noun', answer: 'reading-passages', revealAt: 2, hint: 'Chọn cụm danh từ “reading passages”; “long” được tách riêng.' },
      { label: 'Adj', answer: 'difficult', revealAt: 2, hint: 'Tính từ nào thể hiện đánh giá?' },
    ],
  },
  {
    id: 'teachers-encourage-students',
    structure: 'S + V + somebody + to V + something',
    instruction: 'Bỏ qua các từ bổ nghĩa rồi tìm mẫu động từ “encourage”.',
    segments: [
      { text: 'Our', context: true },
      { id: 'supportive', text: 'especially supportive' },
      { id: 'teachers', text: 'teachers' },
      { id: 'encourage', text: 'encourage' },
      { id: 'shy', text: 'shy' },
      { id: 'students', text: 'students' },
      { text: 'to', context: true },
      { id: 'ask', text: 'ask' },
      { id: 'questions', text: 'questions' },
      { id: 'in-class', text: 'in class', suffix: '.' },
    ],
    steps: [
      { label: 'S', answer: 'teachers', hint: 'Chọn danh từ chính chỉ người khuyến khích.' },
      { label: 'V', answer: 'encourage', pattern: 'encourage + somebody + to V', hint: 'Động từ chính mang nghĩa “khuyến khích”.' },
      { label: 'Somebody', answer: 'students', revealAt: 2, hint: 'Ai nhận được sự khuyến khích?' },
      { label: 'Verb', answer: 'ask', joinBefore: 'to', revealAt: 2, hint: '“To” đã được cho sẵn; chỉ chọn động từ hành động.' },
      { label: 'Something', answer: 'questions', revealAt: 2, hint: 'Học sinh được khuyến khích hỏi điều gì?' },
    ],
  },
]

export function getPerformance(mistakes) {
  if (mistakes === 0) return { title: 'Exceptional job!', message: 'Bạn đã xác định đúng tất cả thành phần ngay lần đầu tiên. Khả năng phân tích câu của bạn thật xuất sắc!', tone: 'exceptional' }
  if (mistakes <= 3) return { title: 'Well done!', message: 'Bạn chỉ cần thử lại một vài lần và đã hoàn thành rất tốt. Tiếp tục phát huy nhé!', tone: 'great' }
  if (mistakes <= 7) return { title: 'Good effort!', message: 'Bạn đang tiến bộ tốt. Hãy xem lại những mẫu câu cần thử lại và chơi thêm một lượt nhé!', tone: 'good' }
  return { title: 'Keep practising!', message: 'Bạn đã kiên trì hoàn thành thử thách. Hãy đọc lại từng mẫu câu và thử lại—bạn sẽ làm tốt hơn!', tone: 'practice' }
}

export function calculateAccuracy(correctAnswers, mistakes) {
  const checks = correctAnswers + mistakes
  return checks === 0 ? 0 : Math.round((correctAnswers / checks) * 100)
}

export function countComponents(items = challenges) {
  return items.reduce((total, challenge) => total + challenge.steps.length, 0)
}
